version: '3.8'

# Development configuration override for BusBuddy
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # SQL Server Database - Development Configuration
  sqlserver:
    ports:
      - "14330:1433"  # Use a different port to avoid conflicts with local SQL Server
    environment:
      - MSSQL_PID=Developer  # Use Developer edition for more features
      - MSSQL_MEMORY_LIMIT_MB=2048  # Limit memory usage for development
    volumes:
      - ./docker/sql/dev:/docker-entrypoint-initdb.d/dev  # Additional dev-specific scripts
    command: 
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & 
        sleep 30
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -i /docker-entrypoint-initdb.d/init-db.sql
        tail -f /dev/null  # Keep container running
        
  # ASP.NET Core Application - Development Configuration
  webapp:
    build:
      dockerfile: Dockerfile.dev  # Use a development-specific Dockerfile if available
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - DOTNET_USE_POLLING_FILE_WATCHER=1  # Enable hot reload
    volumes:
      - ./:/app  # Mount source for hot-reload development
    ports:
      - "5000:5000"
      - "5001:5001"

  # React Dashboard - Development Configuration
  dashboard:
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000/api
      - PORT=5000
    ports:
      - "3000:3000"  # React app
      - "5050:5000"  # API server
    volumes:
      - ./Forms/busbuddy-dashboard:/app/src  # Mount source for hot-reload development
