// <auto-generated />
using System;
using BusBuddy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusBuddy.Migrations
{
    [DbContext(typeof(BusBuddyContext))]
    [Migration("20250510185500_AddTripsAndAlerts")]
    partial class AddTripsAndAlerts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusBuddy.Models.Entities.ActivityTrip", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ActivityName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("ChaperonCount")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("DepartureTime")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("DestinationId")
                    .HasColumnType("int");

                b.Property<int>("DriverId")
                    .HasColumnType("int");

                b.Property<DateTime>("ReturnTime")
                    .HasColumnType("datetime2");

                b.Property<int?>("RouteId")
                    .HasColumnType("int");

                b.Property<int>("StudentCount")
                    .HasColumnType("int");

                b.Property<int>("VehicleId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("DestinationId");

                b.HasIndex("DriverId");

                b.HasIndex("RouteId");

                b.HasIndex("VehicleId");

                b.ToTable("ActivityTrips");
            });

            modelBuilder.Entity("BusBuddy.Models.Entities.Alert", b =>
            {
                b.Property<int>("AlertId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Message")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("RouteId")
                    .HasColumnType("int");

                b.Property<string>("Severity")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("AlertId");

                b.HasIndex("RouteId");

                b.ToTable("Alerts");
            });

            modelBuilder.Entity("BusBuddy.Models.Entities.Trip", b =>
            {
                b.Property<int>("TripId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                b.Property<int>("DelayMinutes")
                    .HasColumnType("int");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<DateTime>("LastUpdated")
                    .HasColumnType("datetime2");

                b.Property<int>("PassengerCount")
                    .HasColumnType("int");

                b.Property<int>("RouteId")
                    .HasColumnType("int");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("TripId");

                b.HasIndex("RouteId");

                b.ToTable("Trips");
            });

            // Add other existing entities from BusBuddyContextModelSnapshot.cs...

            modelBuilder.Entity("BusBuddy.Models.Entities.Alert", b =>
            {
                b.HasOne("BusBuddy.Models.Entities.Route", "Route")
                    .WithMany()
                    .HasForeignKey("RouteId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Route");
            });

            modelBuilder.Entity("BusBuddy.Models.Entities.Trip", b =>
            {
                b.HasOne("BusBuddy.Models.Entities.Route", "Route")
                    .WithMany()
                    .HasForeignKey("RouteId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Route");
            });
        }
    }
}
