name: Branch Strategy Guide

# This file serves as documentation and workflow for the BusBuddy branch strategy

# Strategy Overview:
# - main: Production-ready code, protected branch
# - develop: Integration branch for features, protected
# - feature/*: New features and enhancements
# - bugfix/*: Bug fixes
# - release/*: Release preparation
# - hotfix/*: Emergency production fixes

on:
  # This workflow can be triggered manually to run checks on any branch
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to validate'
        required: true
        default: 'develop'

jobs:
  validate-branch:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: dotnet restore BusBuddy.sln
      
      - name: Build
        run: dotnet build BusBuddy.sln --no-restore
      
      - name: Test
        run: dotnet test Tests\BusBuddy.Tests.csproj --no-build

  # This job only runs for documentation purposes - it's not actually executed
  branch-guidelines:
    runs-on: ubuntu-latest
    if: false # This job never runs, it's just documentation
    steps:
      - name: Branch Naming & Usage Guidelines
        run: |
          echo "Branch Naming & Usage Guidelines:"
          echo "--------------------------------"
          echo "main - Production code only, protected branch"
          echo "develop - Integration branch for completed features"
          echo "feature/FEATURE-NAME - New features (branch from develop)"
          echo "bugfix/BUG-NAME - Bug fixes (branch from develop)"
          echo "release/VERSION - Release preparation (branch from develop)"
          echo "hotfix/ISSUE-NAME - Emergency fixes (branch from main)"
          echo ""
          echo "Flow:"
          echo "1. Create feature or bugfix branch from 'develop'"
          echo "2. Work on changes locally"
          echo "3. Create pull request to 'develop'"
          echo "4. After approval and testing, merge to 'develop'"
          echo "5. Create release branch when ready to release"
          echo "6. After final testing, merge release to 'main' and back to 'develop'"
          echo "7. For urgent fixes, create hotfix branch from 'main'"
          echo "8. Merge hotfix to both 'main' and 'develop'"
